# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      
    - name: Set up Go '1.23'
      uses: actions/setup-go@v5
      with:
         go-version: ${{ matrix.go-version }}

    - name: Install deps
      run:
        go get github.com/a-h/templ
    
    - name: templ-generator-action
      # uses: capthiron/templ-generator-action@f1f7b5d0b261eccff32fa3fc17cf563d993fee94
      uses: capthiron/templ-generator-action@v1
      with:
        # The directory where to look for .templ files.
        directory: "./internal/views"
        # Flag to enable or disable committing changes.
        # using branch protection breaks this, need PAT to use
        commit: false
        # Custom commit message for the generated code.
        # using default (chore: Generate templ code)
        # Flag to enable or disable formatting the generated code.
        # using default (true)
        # Flag to enable or disable setting up Go.
        # using default (true)
        # The Go version to use.
        go-version: '1.23.x'
        # The templ version to use.
        # using default (latest)
          
    - name: Build
      run:
        templ generate
        go build -v ./...
    
    - name: Run
      run: go run -v ./...
